#Design config
FROM python:3.7.10
RUN apt update

RUN mkdir /code
WORKDIR /code
COPY requirements.txt /code/
RUN pip3 install --upgrade pip

RUN pip3 install -r requirements.txt

COPY . /code/

# WORKDIR /code/api/modules
